name: componentes_lr
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  brasil_fields: ^1.3.1
  camera: ^0.11.0
  collection: ^1.18.0
  diacritic: ^0.1.4
  file_picker: ^8.0.3
  flutter_dotenv: ^5.1.0
  flutter_image_compress: ^2.3.0
  flutter_pdfview: ^1.3.2
  flutter_secure_storage: ^9.2.1
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  http: ^1.2.1
  image: ^4.1.4
  intl: ^0.19.0
  local_auth: ^2.2.0
  mask_text_input_formatter: ^2.5.0
  native_device_orientation: ^2.0.3
  package_info_plus: ^8.0.0
  path: ^1.8.3
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  searchfield: ^1.0.1
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  sqflite_sqlcipher: ^3.1.0+1
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  lint: ^2.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
